---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beekeeper-frontend
    component: frontend
    part-of: beehive
    project: beekeeper
    confidentiality: not-defined
    compliance: not-defined
  name: beekeeper-frontend
  namespace: beekeeper
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: beekeeper-frontend
  template:
    metadata:
      labels:
        app: beekeeper-frontend
        component: frontend
        part-of: beehive
        project: beekeeper
        confidentiality: not-defined
        compliance: not-defined
    spec:
      imagePullSecrets:
        - name: beekeeper-pull-token
      containers:
        - name: webserver
          image: registry.login.no/tekkom/web/beehive/beekeeper/frontend:1.5.12-dev
          imagePullPolicy: IfNotPresent
          env:
            - name: BASE_URL
              value: https://authentik.login.no
            - name: API_URL
              value: http://beekeeper-api.beekeeper.svc.cluster.local:8080/api
            - name: NEXT_PUBLIC_BROWSER_API
              value: https://api.beekeeper.login.no/api
            - name: CDN_URL
              value: https://cdn.login.no
            - name: BTG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: beekeeper-secrets
                  key: BTG_TOKEN
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: beekeeper-secrets
                  key: WEBHOOK_URL
            - name: CRITICAL_ROLE
              valueFrom:
                secretKeyRef:
                  name: beekeeper-secrets
                  key: CRITICAL_ROLE
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - beekeeper-frontend
                topologyKey: kubernetes.io/hostname
