---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: do-auth
  namespace: queenbee
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/internal-test-cluster/items/do-admin-api
