---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: public-api-psql
  namespace: beehive
spec:
  monitoring:
    enablePodMonitor: true
  description: Postgres for Beehive public API
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
  postgresql:
    pg_hba:
      - host all all 10.0.0.0/8 md5
    parameters:
      timezone: "Europe/Oslo"
  bootstrap:
    initdb:
      database: beehive
      owner: beehive
      secret:
        name: beehive-public-api-db-credentials
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-internal-prod-psql-backups/beehive-dev
      s3Credentials:
        accessKeyId:
          name: beehive-pg-backup
          key: access
        secretAccessKey:
          name: beehive-pg-backup
          key: secret

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: beehive-dev-backups
  namespace: beehive
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: public-api-psql
