---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beekeeper-frontend
  namespace: beekeeper
spec:
  interval: 5m
  path: "cluster/beekeeper/frontend"
  dependsOn:
    - name: beekeeper-secrets
      namespace: beekeeper
    - name: beekeeper-api
      namespace: beekeeper
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
