---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: studentbee-secrets
  namespace: studentbee
spec:
  interval: 5m
  path: "cluster/studentbee/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-cluster
    namespace: flux-system
