---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wiki-psql
  namespace: wiki
spec:
  monitoring:
    enablePodMonitor: true
  description: Postgres for Wiki-js
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi
  postgresql:
    parameters:
      timezone: "Europe/Oslo"
  bootstrap:
    initdb:
      database: wiki
      owner: wiki
      secret:
        name: wiki-db-credentials
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://login-infra-dev-psql-backups/wiki
      s3Credentials:
        accessKeyId:
          name: wiki-pg-backup
          key: access
        secretAccessKey:
          name: wiki-pg-backup
          key: secret
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: wiki-psql
  namespace: wiki
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: wiki-psql
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wiki-psql-backup
  namespace: wiki
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: wiki-psql
