---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admin-api
  name: admin-api
  namespace: queenbee
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      imagePullSecrets:
        - name: gitlab-api-pull-token
      containers:
        - image: registry.login.no/tekkom/web/beehive/admin-api:1.1.5-dev@sha256:dfb6a23513a19ba22e00494bf49577b58a0628298d5d72496a905dcf7bb64254
          imagePullPolicy: Always
          name: admin-api
          env:
            - name: PORT
              value: "8080"
            - name: DB_HOST
              value: public-api-psql-rw.beehive.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: beehive
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: public-api-db-credentials
                  key: password
            - name: DB_NAME
              value: beehive
            - name: DB_SSL_MODE
              value: require
            - name: GIN_MODE
              value: debug
            - name: TLS_ENABLED
              value: "true"
            - name: TLS_CERT
              value: /tls/tls.crt
            - name: TLS_KEY
              value: /tls/tls.key
            - name: OAUTH2_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: admin-api-auth
                  key: client_id
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-api-auth
                  key: client_secret
            - name: OAUTH2_REDIRECT_URL
              value: https://queenbee-api-dev.login.no/v1/oauth2/callback
            - name: OAUTH2_FRONTEND_REDIRECT_URL
              value: https://queenbee-dev.login.no/login
            - name: OAUTH2_AUTHENTIK_BASE_URL
              value: https://authentik.login.no
            - name: TOKEN_ACCESS_TOKEN_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-api-auth
                  key: access_token_key
            - name: TOKEN_REFRESH_TOKEN_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: admin-api-auth
                  key: refresh_token_key
            - name: TOKEN_ACCESS_TOKEN_DURATION
              value: 15m
            - name: TOKEN_REFRESH_TOKEN_DURATION
              value: 12h
            - name: DO_ACCESS_KEY_ID
              value: DO801ADRKWK7UTX6RHYV
            - name: DO_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: DO-auth
                  key: credential
            - name: DO_BASE_URL
              value: https://ams3.digitaloceanspaces.com
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tls-certs
              readOnly: true
              mountPath: "/tls"
        - name: redis
          image: redis:7.4.1-alpine3.20@sha256:c1e88455c85225310bbea54816e9c3f4b5295815e6dbf80c34d40afc6df28275
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: 6379tcp
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - admin-api
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: tls-certs
          secret:
            secretName: backend-self-signed
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
