---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dizambee-frontend
    component: frontend
    part-of: beehive
    project: dizambee
    confidentiality: not-defined
    compliance: not-defined
  name: dizambee-frontend
  namespace: dizambee
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: dizambee-frontend
  template:
    metadata:
      labels:
        app: dizambee-frontend
        component: frontend
        part-of: beehive
        project: dizambee
        confidentiality: not-defined
        compliance: not-defined
    spec:
      imagePullSecrets:
        - name: gitlab-deploy-key-dizambee
      containers:
        - name: webserver
          image: registry.login.no/tekkom/web/beehive/dizambee/frontend:1.0.5-dev@sha256:362841a581faa1e20ba1c06c33a4011e786749fa2f67cecfd8849a861024fd39
          imagePullPolicy: IfNotPresent
          command:
            - npm
            - start
          env:
            - name: API_URL
              value: http://dizambee-api.dizambee.svc.cluster.local:8080/api
            - name: BROWSER_API
              value: http://dev-dizambee-api.login.no:8080/api
          ports:
            - containerPort: 3000
              name: 3000tcp
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 5
          resources:
            requests:
              memory: 128Mi
              cpu: 125m
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: kubernetes.io/hostname
