---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redirect-old-domains
  namespace: redirect-namespace
spec:
  secretName: redirect-old-domains-cert
  issuerRef:
    kind: Issuer
    name: do-issuer-prod
  dnsNames:
    - "linjeforeningen.it"
    - "cyberdagen.net"
    - "cyberdagen.no"
    - "cyberdagene.net"
    - "cyberdagene.no"
    - "fadderuka.com"
    - "fadderuka.org"
    - "karrieredag.no"
    - "login-ntnu.no"
    - "login.coffee"
    - "loginlf.no"
    - "loginntnu.no"
    - "logintnu.no"
    - "logntnu.com"
    - "logout.no"
    - "ntnulogin.no"


# needs to ne changed: https://gitlab.login.no/tekkom/infrastructure/kubernetes/internal-test-cluster/-/blob/de329b9a9c19bf351eee9b8e0e578255f5a00882/cluster/external-dns/external-dns.yaml#L26