---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: automated-notifications-pull-secret
  namespace: automated-notifications
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/internal-test-cluster/items/automated-notifications-pull-secret"
