---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: zammad-psql
  namespace: zammad
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: zammad-recovery

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: zammad-revocery-psql-backup
  namespace: zammad
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  cluster:
    name: zammad-recovery
