---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraints
  namespace: workerbee
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 100m
        memory: 64Mi
      type: Container
