---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beeformed-secrets
  namespace: beeformed
spec:
  interval: 5m
  path: "cluster/beeformed/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-cluster
    namespace: flux-system
