---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1pwdsecrets
  namespace: zammad
spec:
  interval: 5m
  path: "cluster/zammad/secrets"
  dependsOn:
    - name: 1password-connect
      namespace: 1pwd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
