---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin-api-certs
  namespace: queenbee
spec:
  interval: 5m
  path: "cluster/queenbee/certificate"
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-cluster
    namespace: flux-system
