---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: queenbee-frontend
  namespace: queenbee
spec:
  interval: 5m
  path: "cluster/queenbee/frontend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
