---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - backend/backend.yaml
  - backend/backend_svc.yaml
  - frontend/frontend.yaml
  - frontend/frontend_svc.yaml
