---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: "2025.6.0"
      sourceRef:
        kind: HelmRepository
        name: authentik-repo
        namespace: authentik
      interval: 5m
  values:
    global:
      addPrometheusAnnotations: true
      env:
        - name: AUTHENTIK_STORAGE__MEDIA__BACKEND
          value: s3
        - name: AUTHENTIK_STORAGE__MEDIA__S3__USE_SSL
          value: "true"
        - name: AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT
          value: https://login-authentik-media.ams3.digitaloceanspaces.com
        - name: AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: do-spaces
              key: accesstoken
        - name: AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: do-spaces
              key: secretkey
        - name: AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME
          value: login-authentik-media
        - name: AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN
          value: login-authentik-media.ams3.digitaloceanspaces.com/login-authentik-media
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST
          value: authentik-restore-psql-ro.authentik-dev.svc.cluster.local
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME
          value: authentik
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PORT
          value: "5432"
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER
          valueFrom:
            secretKeyRef:
              name: authentik-db-credentials
              key: username
        - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-db-credentials
              key: password
      volumes:
        - name: authentik-certificate
          projected:
            sources:
              - secret:
                  name: authentik-certificate
                  items:
                    - key: tls.crt
                      path: authentik_cert.pem
                    - key: tls.key
                      path: authentik_cert.key
        - name: postgres-creds
          secret:
            secretName: authentik-db-credentials
        - name: secret-key
          secret:
            secretName: authentik-secret-key
        - name: email-sec
          secret:
            secretName: authentik-smtp-server-credentials
      volumeMounts:
        - name: authentik-certificate
          mountPath: "/certs"
          readOnly: true
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
        - name: secret-key
          mountPath: /secret-key
          readOnly: true
        - name: email-sec
          mountPath: /email-sec
          readOnly: true
    authentik:
      email:
        host: "secure.emailsrvr.com"
        port: 465
        username: file:///email-sec/username
        password: file:///email-sec/password
        use_ssl: true
        timeout: 30
        from: "Authentik - Login <authentik@login.no>"
      disable_update_check: true
      disable_startup_analytics: true
      secret_key: file:///secret-key/password
      error_reporting:
        enabled: false
        send_pii: false
      postgresql:
        host: authentik-restore-psql-rw.authentik-dev.svc.cluster.local
        name: authentik
        port: 5432
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
    postgresql:
      enabled: false
    redis:
      enabled: true
    server:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus
      env:
        - name: AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS
          value: 10.0.0.0/8
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "2Gi"
          cpu: "2"
      autoscaling:
        enabled: true
        minReplicas: 0
        maxReplicas: 0
        targetCPUUtilizationPercentage: 80
      ingress:
        ingressClassName: nginx-external
        annotations:
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
          nginx.ingress.kubernetes.io/upgrade-proxy: "true"
          nginx.ingress.kubernetes.io/enable-websockets: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
        enabled: true
        https: true
        tls:
          - hosts:
              - authentik-dev.login.no
        hosts:
          - authentik-dev.login.no
      pdb:
        enabled: true
        minAvailable: 1
    worker:
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "2Gi"
          cpu: "2"
      autoscaling:
        enabled: true
        minReplicas: 0
        maxReplicas: 0
        targetCPUUtilizationPercentage: 80
      pdb:
        enabled: true
        minAvailable: 1
