---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/tls
metadata:
  name: authentik-certificate
  namespace: authentik
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: "vaults/internal-test-cluster/items/authentik-cert"

